#! /bin/sh
nitrogen --restore &
dunst &
picom &
flameshot &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
bspc monitor eDP -d 󰎤 󰎧 󰎪 󰎭 󰎱 󰎳 󰎶


setxkbmap -option grp:alt_shift_toggle us,ua,ru &

bspc config border_width        3
bspc config window_gap		6

bspc config normal_border_color "#181825"
bspc config active_border_color "#e78284"
bspc config focused_border_color "#8caaee"

bspc config presel_feedback_color "##ef9f76"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle	 true
bspc config single_monocle	true

bspc rule -a Chromium desktop='^4'
bspc rule -a firefox desktop='^4'
bspc rule -a telegram-desktop desktop follow=off state=floating follow=off ='^5'
bspc rule -a qBittorrent desktop='^3'
bspc config focus_follows_pointer true

$HOME/.config/polybar/launch.sh

